[package]
name = "chip8dynarec"
version = "0.1.0"
authors = ["rwilfried <wilfried.rabouin@gmail.com>"]

[dependencies]
rand = "0.3"
sdl2 = "0.30"
libc = "0.2"

[features]
# no features by default
default = []
debugger = []
interpreter = []
